name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 40
    strategy:
      matrix:
        include:
          # - os: "linux"
          #   name: "ubuntu-18-04"
          #   runs-on: "ubuntu-18-04"
          - os: "linux"
            name: "latest"
            runs-on: "ubuntu-latest"
          - os: "mac"
            name: "arm64"
            runs-on: "mac-silicon"
          - os: "mac"
            name: "amd64"
            runs-on: "macos-13"
          # - os: "windows"
          #   name: "amd64"
          #   runs-on: "windows-cuda-12-0"
          - os: "windows"
            name: "latest"
            runs-on: "windows-latest"

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v3

      - name: Install OpenSSL on Ubuntu
        if: matrix.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl libssl-dev
      
      - name: Install make on Windows
        if: runner.os == 'windows'
        run: |
          choco install make -y

      - name: Install dependencies
        run: |
          make install-dependencies

      - name: Build engine 
        run: |
          make build-engine

      - name: Build example server
        run: |
          make build-example-server

      - name: Run e2e test
        run: |
          make run-e2e-test

      - name: Package
        run: |
          make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cortex.python-runtime-${{ matrix.os }}-${{ matrix.name }}
          path: ./cortex.python-runtime.tar.gz
